# Stage 1: Base Image
# ashleykza/a1111:1.10.0.post7
# FROM nvidia/cuda:12.4.1-cudnn-devel-ubuntu22.04
FROM nvidia/cuda:12.8.1-cudnn-devel-ubuntu22.04

# Setting timezome. This saves time when installing python. 
# RUN ln -snf /usr/share/zoneinfo/$CONTAINER_TIMEZONE /etc/localtime && echo $CONTAINER_TIMEZONE > /etc/timezone

RUN apt update && \
  apt upgrade -y && \
  apt install -y \
  # Python:
  python3-dev \
  python3-pip \
  # python3.12-venv \
  python3.10-venv 

COPY . .
RUN chmod +x ./installContainer.sh

RUN mkdir -p workspace

# RUN echo "$PWD"
# ENTRYPOINT ["ls"]
# ENTRYPOINT ["./installComfyUI.sh"]
# CMD ["supervisord","-c","./service_script.conf"]
CMD ["bash","/installContainer.sh"]

