# Stage 1: Base Image
# ashleykza/a1111:1.10.0.post7
# FROM nvidia/cuda:12.4.1-cudnn-devel-ubuntu22.04
FROM runpod/pytorch:1.0.2-cu1300-torch280-ubuntu2404


ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONUNBUFFERED=1

COPY . .
RUN chmod +x ./installContainer.sh

RUN mkdir -p workspace

# RUN echo "$PWD"
# ENTRYPOINT ["ls"]
# ENTRYPOINT ["./installComfyUI.sh"]
# CMD ["supervisord","-c","./service_script.conf"]
CMD ["bash","/installContainer.sh"]

