version: '3.8'

services:
  runpod-comfy-ui:
    # image: walmann/runpodcomfyui:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - /workspace:/workspace
    ports:
      - "3000:3001"
      - "3923:3923"
    environment:
      JUPYTER_PASSWORD: "Jup1t3R!"
      ENABLE_TENSORBOARD: "1"
    restart: unless-stopped